openapi: 3.0.3
info:
  title: 新光醫院 單張交換 to FHIR - API 使用說明書
  description: |-
    新光醫院 交換單張 XML to FHIR :

            API 0.1.0 based on the OpenAPI 3.0 specification.

    概述 : 

            將現行交換單張XML轉成FHIR 並存入FHIR Server

    對象 :

            1.出院病摘
            2.門診病歷(第二階段)
            3.血液檢驗(第二階段)
            4.檢查報告(第二階段)

    方法 : 
            
            依現行衛生福利部電子病歷FHIR推動專區公告標準，將欄位對應至FHIR相對resourceType欄位，存入FHIR Server

    配套 : 

            上傳後至FHIR Portal，查詢上傳資料狀態

    注意事項 :
    
            1.Request body 內 Example Value 與 Schema 僅為說明格式，section 及 entry 重複格式不逐一說明，詳細說明請參照範例資料註解
            2.測試時請由下方連結下載範例資料複製貼上至 Request body 內 Example Value 執行
            3.後續維護更新責任者-緯謙科技

    範例資料:
    - [出院病摘單CDAR2 XML測試資料](/DischargeSummary)
    - [門診病例CDAR2 XML測試資料](/VisitNote)
    - [血液檢驗CDAR2 XML測試資料(預留)]
    
    服務連結:
    - [SKH FHIR Portal(暫定)](https://sit-fhir.skh.org.tw)
    - [SKH FHIR API](https://sit-fhir.skh.org.tw/api)
    - [SKH API swagger(暫定)](https://sit-fhir.skh.org.tw/swagger)
    
    FHIR標準參照:
    - [衛生福利部電子病歷FHIR推動專區](https://emr.mohw.gov.tw/myemr/fhir.html)
    
    維護專區:
    - [緯謙科技](https://www.wiadvance.com/)    
    - [專案負責部門 : T02300 ]
    - [電話 : 02-66126262]
    - [分機 : 14711 ]

  contact:
    email: Gojim.Yu@wiadvance.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
externalDocs:
  description: Find out more about 緯謙科技
  url: https://www.wiadvance.com/
servers:
  - url: https://sit-fhir.skh.org.tw/api
tags:
  - name: 交換單張
    description: 公告交換單張標準
    externalDocs:
      description: 衛生福利部電子病歷FHIR推動專區
      url: https://emr.mohw.gov.tw/myemr/fhir.html
paths:
  /:
    get:
      tags:
        - Server
      summary: 回傳伺服器狀態
      description: 回傳伺服器狀態

      operationId: getInventory
      parameters: []
      responses:
        '200':
          description: "Server Status : run (正常)"
        '500':
          description: "internal server error (內部伺服器錯誤)"

  /DischargeSummary/{DischargeSummary_Id}:
    post:
      tags:
        - 出院病摘單
      summary: 新增出院病摘單資料
      description: 將出院病摘單XML轉為FHIR並儲存至FHIR server
      operationId: add_DischargeSummary
      parameters: 
        - name: DischargeSummary_Id
          in: path
          description: ID of DischargeSummary to return
          required: true
          schema:
            type: string
            format: string
      requestBody:
        description: Composition_DischargeSummary
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/ContentPackage'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_DischargeSummary_ApiResponse_JSON'
      security:
         - api_key: []
    get:
      tags:
        - 出院病摘單
      summary: 取得出院病摘單資料
      description: 取得出院病摘單資料
      operationId: get_DischargeSummary
      parameters: 
        - name: DischargeSummary_Id
          in: path
          description: ID of DischargeSummary to return
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_DischargeSummary_ApiResponse_JSON'
    put:
      tags:
        - 出院病摘單
      summary: 更新出院病摘單資料
      description: 更新出院病摘單資料
      operationId: put_DischargeSummary
      parameters: 
        - name: DischargeSummary_Id
          in: path
          description: ID of DischargeSummary to update
          required: true
          schema:
            type: string
            format: string
      requestBody:
        description: Composition_DischargeSummary
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Composition_DischargeSummary_ApiResponse_JSON'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_DischargeSummary_ApiResponse_JSON'
      security:
        - wiadvance_auth:
            - put
    delete:
      tags:
        - 出院病摘單
      summary: 刪除出院病摘單資料
      description: 刪除出院病摘單資料
      operationId: delete_DischargeSummary
      parameters: 
        - name: DischargeSummary_Id
          in: path
          description: ID of DischargeSummary to delete
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: OperationOutcome
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delete_Reaponse_Json'
      security:
        - wiadvance_auth:
            - delete
        
  /VisitNote/{VisitNote_Id}:
    post:
      tags:
        - 門診病例
      summary: 新增門診病例資料資料(預留)
      description: 將門診病例XML轉為FHIR並儲存至FHIR server
      operationId: add_VisitNote
      parameters: 
        - name: VisitNote_Id
          in: path
          description: ID of VisitNote to add
          required: true
          schema:
            type: string
            format: string
      requestBody:
        description: Composition_VisitNote
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/ContentPackage'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
      security:
         - api_key: []
    get:
      tags:
        - 門診病例
      summary: 取得門診病例資料(預留)
      description: 取得門診病例資料
      operationId: get_VisitNote
      parameters: 
        - name: VisitNote_Id
          in: path
          description: ID of VisitNote to return
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
    put:
      tags:
        - 門診病例
      summary: 更新門診病例資料(預留)
      description: 更新門診病例資料
      operationId: put_VisitNote
      parameters: 
        - name: VisitNote_Id
          in: path
          description: ID of BloodExamination to delete
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
      security:
        - wiadvance_auth:
            - put
    delete:
      tags:
        - 門診病例
      summary: 刪除門診病例資料(預留)
      description: 刪除門診病例資料
      operationId: delete_VisitNote
      parameters: 
        - name: VisitNote_Id
          in: path
          description: ID of VisitNote to delete
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: OperationOutcome
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delete_Reaponse_Json'
      security:
        - wiadvance_auth:
            - delete
  /BloodExamination/{BloodExamination_Id}:
    post:
      tags:
        - 血液檢驗
      summary: 新增血液檢驗資料(預留)
      description: 將血液檢驗轉為FHIR並儲存至FHIR server
      operationId: add_BloodExamination
      parameters: 
        - name: BloodExamination_Id
          in: path
          description: ID of BloodExamination to add
          required: true
          schema:
            type: string
            format: string
      requestBody:
        description: Composition_BloodExamination
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContentPackage'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
      security:
         - api_key: []
    get:
      tags:
        - 血液檢驗
      summary: 取得血液檢驗資料(預留)
      description: 取得血液檢驗資料(預留)
      operationId: get_BloodExamination
      parameters: 
        - name: BloodExamination_Id
          in: path
          description: ID of BloodExamination to return
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
    put:
      tags:
        - 血液檢驗
      summary: 更新血液檢驗資料(預留)
      description: 更新血液檢驗資料(預留)
      operationId: put_BloodExamination
      parameters: 
        - name: BloodExamination_Id
          in: path
          description: ID of BloodExamination to update
          required: true
          schema:
            type: string
            format: string
      requestBody:
        description: Composition_BloodExamination
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Composition_VisitNote_ApiResponse_JSON'
      security:
        - wiadvance_auth:
            - put
    delete:
      tags:
        - 血液檢驗
      summary: 刪除血液檢驗資料(預留)
      description: 刪除血液檢驗資料(預留)
      operationId: delete_BloodExamination
      parameters: 
        - name: BloodExamination_Id
          in: path
          description: ID of BloodExamination to delete
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: OperationOutcome
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delete_Reaponse_Json'
      security:
        - wiadvance_auth:
            - delete

components:
  schemas:
    ContentPackage:
      type: object
      properties:
        id:
          type: string
          example: I-20230223201079620
          xml:
            attribute: true
        xmlns:
          type: string
          example: urn:hl7-org:v3
          xml:
            attribute: true
        xmlns:xmime:
          type: string
          example: http://www.w3.org/2005/05/xmlmime
          xml:
            attribute: true
        xmlns:xsi:
          type: string
          example: http://www.w3.org/2001/XMLSchema-instance
          xml:
            attribute: true
        xsi:schemaLocation:
          type: string
          example: http://www.hl7.org.tw/EMR/CDocumentPayload/v1.0 CDA_Package_V01.xsd
          xml:
            attribute: true
        cdp:ContentContainer:
          type: object
          properties:
            range:
              type: integer
              xml:
                attribute: true
            cdp:StructuredContent:
              type: object
              properties:
                ClinicalDocument:
                  type: object
                  properties:
                    classCode:
                      type: string
                      example: DOCCLIN
                      xml:
                        attribute: true
                    moodCode:
                      type: string
                      example: EVN
                      xml:
                        attribute: true
                    xmlns:
                      type: string
                      example: urn:hl7-org:v3
                      xml:
                        attribute: true
                    xmlns:voc:
                      type: string
                      example: urn:hl7-org:v3/voc
                      xml:
                        attribute: true
                    xmlns:xsi:
                      type: string
                      example: http://www.w3.org/2001/XMLSchema-instance
                      xml:
                        attribute: true
                    xsi:schemaLocation:
                      type: string
                      example: urn:hl7-org:v3 CDA.xsd
                      xml:
                        attribute: true
                    typeId:
                      type: object
                      properties:
                        extension:
                          type: string
                          example: POCD_HD000040
                          xml:
                            attribute: true
                        root:
                          type: string
                          example: 2.16.840.1.113883.1.3
                          xml:
                            attribute: true
                    templateId:
                      type: object
                      properties:
                        extension:
                          type: string
                          example: 115_V108.0
                          xml:
                            attribute: true
                        root:
                          type: string
                          example: 2.16.886.101.20003.20014
                          xml:
                            attribute: true
                    id:
                      type: object
                      properties:
                        extension:
                          type: string
                          example: '15168590.20230313170013'
                          xml:
                            attribute: true
                        root:
                          type: string
                          example: 2.16.886.104.101237.100000
                          xml:
                            attribute: true
                    code:
                      type: object
                      properties:
                        code:
                          type: string
                          example: "18842-5"
                          xml:
                            attribute: true
                        codeSystem:
                          type: string
                          example: "2.16.840.1.113883.6.1"
                          xml:
                            attribute: true
                        codeSystemName:
                          type: string
                          example: "LOINC"
                          xml:
                            attribute: true
                        displayName:
                          type: string
                          example: "Discharge Summary"
                          xml:
                            attribute: true
                    title:
                        type: string
                        example: ""
                    effectiveTime:
                      type: object
                      properties:
                        value:
                          type: string
                          example: "20230313170013"
                          xml:
                            attribute: true
                    confidentialityCode:
                      type: object
                      properties:
                        code:
                          type: string
                          example: "N"
                          xml:
                            attribute: true
                        codeSystem:
                          type: string
                          example: "2.16.840.1.113883.5.25"
                          xml:
                            attribute: true
                        codeSystemName:
                          type: string
                          example: "Confidentiality"
                          xml:
                            attribute: true
                        displayName:
                          type: string
                          example: "normal"
                          xml:
                            attribute: true
                    languageCode:
                      type: object
                      properties:
                        code:
                          type: string
                          example: "zh-TW"
                          xml:
                            attribute: true
                    recordTarget:
                      type: object
                      properties:
                        typeCode:
                          type: string
                          example: "RCT"
                          xml:
                            attribute: true
                        contextControlCode:
                          type: string
                          example: "OP"
                          xml:
                            attribute: true
                        patientRole:
                          type: object
                          properties:
                            classCode:
                              type: string
                              example: "PAT"
                              xml:
                                attribute: true
                            id:
                              type: object
                              properties:
                                extension:
                                  type: string
                                  example: "15168590"
                                  xml:
                                    attribute: true
                                root:
                                  type: string
                                  example: "2.16.886.104.101237.100000"
                                  xml:
                                    attribute: true
                            patient:
                              type: object
                              properties:
                                classCode:
                                  type: string
                                  example: "PSN"
                                  xml:
                                    attribute: true
                                determinerCode:
                                  type: string
                                  example: "INSTANCE"
                                  xml:
                                    attribute: true
                                id:
                                  type: object
                                  properties:
                                    extension:
                                      type: string
                                      example: "A123456789"
                                      xml:
                                        attribute: true
                                    root:
                                      type: string
                                      example: "2.16.886.101.20003.20001"
                                      xml:
                                        attribute: true
                                name:
                                  type: string
                                  example: "李OO"
                                administrativeGenderCode:
                                  type: object
                                  properties:
                                    code:
                                      type: string
                                      example: "M"
                                      xml:
                                        attribute: true
                                    codeSystem:
                                      type: string
                                      example: "2.16.840.1.113883.5.1"
                                      xml:
                                        attribute: true
                                    codeSystemName:
                                      type: string
                                      example: "AdministrativeGender"
                                      xml:
                                        attribute: true
                                birthTime:
                                  type: object
                                  properties:
                                    value:
                                      type: string
                                      example: "19510712"
                                      xml:
                                        attribute: true
                            providerOrganization:
                                  type: object
                                  properties:
                                    classCode:
                                      type: string
                                      example: "ORG"
                                      xml:
                                        attribute: true
                                    determinerCode:
                                      type: string
                                      example: "INSTANCE"
                                      xml:
                                        attribute: true
                                    codeSystemName:
                                      type: string
                                      example: "AdministrativeGender"
                                      xml:
                                        attribute: true
                                    id:
                                      type: object
                                      properties:
                                        extension:
                                          type: string
                                          example: "1101150011"
                                          xml:
                                            attribute: true
                                        root:
                                          type: string
                                          example: "2.16.886.101.20003.20014"
                                          xml:
                                            attribute: true
                                    name:
                                      type: string
                                      example: "醫院名稱"
                    author:
                      type: object
                      properties:
                        typeCode:
                          type: string
                          example: "AUT"
                          xml:
                            attribute: true
                        contextControlCode:
                          type: string
                          example: "OP"
                          xml:
                            attribute: true
                        time:
                          type: object
                          properties:
                            value:
                              type: string
                              example: "20230302111302"
                              xml:
                                attribute: true
                        assignedAuthor:
                          type: object
                          properties:
                            classCode:
                              type: string
                              example: "ASSIGNED"
                              xml:
                                attribute: true
                        id:
                          type: object
                          properties:
                            extension:
                              type: string
                              example: "A11XXXX053"
                              xml:
                                attribute: true
                            root:  
                              type: string
                              example: "2.16.886.104.101237.100000"
                              xml:
                                attribute: true
                        assignedPerson:
                          type: object
                          properties:
                            classCode:
                              type: string
                              example: "PSN"
                              xml:
                                attribute: true
                            determinerCode:  
                              type: string
                              example: "INSTANCE"
                              xml:
                                attribute: true
                            name:
                              type: string
                              example: "A11XXXX053"
                    custodian:
                      type: object
                      properties:
                        typeCode:
                          type: string
                          example: "CST"
                          xml:
                            attribute: true
                        assignedCustodian:
                          type: object
                          properties:
                            classCode:
                              type: string
                              example: "ASSIGNED"
                              xml:
                                attribute: true
                            representedCustodianOrganization:
                              type: object
                              properties:
                                classCode:
                                  type: string
                                  example: "ORG"
                                  xml:
                                    attribute: true
                                determinerCode:  
                                  type: string
                                  example: "INSTANCE"
                                  xml:
                                    attribute: true
                                id:
                                  type: object
                                  properties:
                                    extension:
                                      type: string
                                      example: "1101150011"
                                      xml:
                                        attribute: true
                                    root:  
                                      type: string
                                      example: "2.16.886.101.20003.20014"
                                      xml:
                                        attribute: true
                                name:
                                  type: string
                                  example: "醫院名稱"
                    participant:
                      type: object
                      properties:
                        typeCode:
                          type: string
                          example: "REFB"
                          xml:
                            attribute: true
                        associatedEntity:
                          type: object
                          properties:
                            classCode:
                              type: string
                              example: "PROV"
                              xml:
                                attribute: true
                            id:
                              type: object
                              properties:
                                extension:
                                  type: string
                                  example: "null"
                                  xml:
                                    attribute: true
                                root:  
                                  type: string
                                  example: "2.16.886.101.20003.20014"
                                  xml:
                                    attribute: true
                                scopingOrganization:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                      example: ""
                    componentOf:
                      type: object
                      properties:
                        typeCode:
                          type: string
                          example: "COMP"
                          xml:
                            attribute: true
                        encompassingEncounter:
                          type: object
                          properties:
                            classCode:
                              type: string
                              example: "ENC"
                              xml:
                                attribute: true
                            moodCode:
                              type: string
                              example: "EVN"
                              xml:
                                attribute: true
                            effectiveTime:
                              type: object
                              properties:
                                encompassingEncounter:
                                  type: object
                                  properties:
                                    low:
                                      type: string
                                      example: "ENC"
                                      xml:
                                        attribute: true
                                    moodCode:
                                      type: string
                                      example: "EVN"
                                      xml:
                                        attribute: true
                                    effectiveTime:
                                      type: object
                                      properties:
                                        low:
                                          type: object
                                          properties:
                                            classCode:
                                              type: string
                                              example: "20230223"
                                              xml:
                                                attribute: true
                                        high:
                                          type: object
                                          properties:
                                            classCode:
                                              type: string
                                              example: "20230302"
                                              xml:
                                                attribute: true
                                    location:
                                      type: object
                                      properties:
                                        typeCode:
                                              type: string
                                              example: "LOC"
                                              xml:
                                                attribute: true
                                        healthCareFacility:
                                          type: object
                                          properties:
                                            classCode:
                                              type: string
                                              example: "SDLOC"
                                              xml:
                                                attribute: true
                                            location:
                                              type: object
                                              properties:
                                                classCode:
                                                  type: string
                                                  example: "PLC"
                                                  xml:
                                                    attribute: true
                                                determinerCode:
                                                  type: string
                                                  example: "INSTANCE"
                                                  xml:
                                                    attribute: true
                                                name:
                                                  type: string
                                                  example: "血液腫瘤科"
                                                addr:
                                                  type: string
                                                  example: "8223"
                    component:
                      type: object
                      properties:
                        typeCode:
                              type: string
                              example: "COMP"
                              xml:
                                attribute: true
                        contextConductionInd:
                              type: string
                              example: "true"
                              xml:
                                attribute: true
                        structuredBody:
                          type: object
                          properties:
                            classCode:
                              type: string
                              example: "DOCBODY"
                              xml:
                                attribute: true
                            moodCode:
                              type: string
                              example: "EVN"
                              xml:
                                attribute: true
                            component:
                              properties:
                                typeCode:
                                  type: string
                                  example: "COMP"
                                  xml:
                                    attribute: true
                                contextConductionInd:
                                  type: string
                                  example: "true"
                                  xml:
                                    attribute: true
                                section:
                                  properties:
                                    classCode:
                                      type: string
                                      example: "DOCSECT"
                                      xml:
                                        attribute: true
                                    moodCode:
                                      type: string
                                      example: "EVN"
                                      xml:
                                        attribute: true
                                    code:
                                      properties:
                                        code:
                                          type: string
                                          example: "46241-6"
                                          xml:
                                            attribute: true
                                        codeSystem:
                                          type: string
                                          example: "2.16.840.1.113883.6.1"
                                          xml:
                                            attribute: true
                                        codeSystemName:
                                          type: string
                                          example: "LOINC"
                                          xml:
                                            attribute: true
                                        displayName:
                                          type: string
                                          example: "Hospital admission Dx"
                                          xml:
                                            attribute: true
                                        title:
                                          type: string
                                          example: "住院臆斷"
                                        text :
                                          properties:
                                            paragraph:
                                              type: string
                                              example: "文字敘述"
                                        entry :
                                          properties:
                                            observation:
                                              type: object
                                              properties:
                                                moodCode:
                                                  type: string
                                                  example: "EVN"
                                                  xml:
                                                    attribute: true
                                                classCode:
                                                  type: string
                                                  example: "COND"
                                                  xml:
                                                    attribute: true
                                                code:
                                                  type: object
                                                  properties:
                                                    code:
                                                      type: string
                                                      example: "C9310"
                                                      xml:
                                                        attribute: true
                                                    displayName:
                                                      type: string
                                                      example: "Chronic myelomonocytic leukemia not having achieved remission"
                                                      xml:
                                                        attribute: true
                                                    codeSystemName:
                                                      type: string
                                                      example: "ICD10CM"
                                                      xml:
                                                        attribute: true
                                                    codeSystem:
                                                      type: string
                                                      example: "2.16.840.1.113883.6.3"
                                                      xml:
                                                        attribute: true
                                                text:
                                                  type: string
                                                  example: "False"
                                            observationMedia:
                                              type: object
                                              properties:
                                                moodCode:
                                                  type: string
                                                  example: "EVN"
                                                  xml:
                                                    attribute: true
                                                classCode:
                                                  type: string
                                                  example: "DGIMG"
                                                  xml:
                                                    attribute: true
                                                value:
                                                  type: object
                                                  properties:
                                                    mediaType:
                                                      type: string
                                                      example: "image/jpeg"
                                                      xml:
                                                        attribute: true
                                                    representation:
                                                      type: string
                                                      example: "B64"
                                                      xml:
                                                        attribute: true

      xml:
        prefix: cdp
        namespace: http://www.hl7.org.tw/EMR/CDocumentPayload/v1.0
    Composition_VisitNote_ApiResponse_JSON:
      type: object
      properties:
        resourceType:
          type: string
        id:
          type: string
        meta:
          type: object
          properties:
            versionId:
              type: string
            lastUpdated:
              type: string
            source:
              type: string
        language:
          type: string
        text:
          type: object
          properties:
            status:
              type: string
            div:
              type: string
        status:
          type: string
        type:
          type: object
          properties:
            coding:
              type: object
              properties:
                system:
                  type: string
                code:
                  type: string
                display:
                  type: string
        subject:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        encounter:
          type: object
          properties:
            reference:
              type: string
        date:
          type: string
        author:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        title:
          type: string
        confidentiality:
          type: string
        attester:
          type: object
          properties:
            mode:
              type: string
            time:
              type: string
        custodian:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        section:
          type: object
          properties:
            title:
              type: string
            code:
              type: object
              properties:
                coding:
                  type: object
                  properties:
                    system:
                      type: string
                    code:
                      type: string
                    display:
                      type: string
            text:
              type: object
              properties:
                status:
                  type: string
                div:
                  type: string
            entry:
              type: object
              properties:
                reference:
                  type: string
      example:
        resourceType: Composition
        id: '1'
        meta:
          versionId: '1'
          lastUpdated: '2023-03-08T06:42:02.621+00:00'
          source: '#E3Wp8IdPMe08QsvA'
        language: zh-TW
        text:
          status: generated
          div: '<div xmlns=\"http://www.w3.org/1999/xhtml\">\t    \n\t\t\t<table border=\"1\">\n\t\t\t\t<caption>門診病歷</caption>\n\t\t\t\t<tr><th>身分證字號</th><th>病歷號</th><th>病人姓名</th><th>性別</th><th>出生日期</th><th>文件列印日期</th><th>醫師姓名</th><th>醫師紀錄日期時間</th><th>醫院名稱</th><th>科別</th><th>門診日期</th></tr>\n\t\t\t\t<tr><td>Z123456789</td><td>123456</td><td>趙錢孫</td><td>男</td><td>1997-01-01</td><td>2010-09-04</td><td>賴一施 </td><td>2010-09-04</td><td>國立臺灣大學醫學院附設醫院</td><td>家醫科</td><td>2010-08-10</td></tr>\n\t\t\t</table>\n\t\t</div>'
        status: preliminary
        type:
          coding:
            - system: http://loinc.org
              code: 28579-1
              display: Visit note
        subject:
          reference: https://fhirtest.uhn.ca/baseR4/Patient/129257
          display: 趙錢孫
        encounter:
          reference: https://fhirtest.uhn.ca/baseR4/Encounter/129801
        date: 2010-08-01T11:34:00
        author:
          - reference: https://fhirtest.uhn.ca/baseR4/Practitioner/129288
            display: 賴一施
        title: 門診病歷
        confidentiality: N
        attester:
          - mode: professional
            time: 2010-07-31
        custodian:
          reference: https://fhirtest.uhn.ca/baseR4/Organization/129188
          display: 國立臺灣大學醫學院附設醫院
        section:
          - title: 實驗室檢查紀錄
            code:
              coding:
                - system: http://loinc.org
                  code: 19146-0
                  display: Reference lab test results
            text:
              status: generated
              div: '<div xmlns=\"http://www.w3.org/1999/xhtml\">\n\t\t\t\t<br/>\n\t\t\t\t<table>\n\t\t\t\t\t<tr><b>實驗室檢查紀錄:病人血型及D抗原性</b></tr>\n\t\t\t\t\t<tr>血型:B</tr>\n\t\t\t\t\t<tr>D抗原性:Rh+</tr>\n\t\t\t\t</table>\n\t\t\t</div>'
            entry:
                - reference: https://fhirtest.uhn.ca/baseR4/Observation/127858
          - title: 出院診斷
            code:
              coding:
                - system: http://loinc.org
                  code: 11535-2
                  display: Hospital discharge Dx Narrative
            text:
              status: generated
              div: '<div xmlns="http://www.w3.org/1999/xhtml"><br/><table><tr><b>出院診斷:</b></tr><tr>結核病(Tuberculosis)</tr></table></div>'
            entry:
              - reference: https://fhirtest.uhn.ca/baseR4/Condition/128907
    Composition_DischargeSummary_ApiResponse_JSON:
      type: object
      properties:
        resourceType:
          type: string
        id:
          type: string
        meta:
          type: object
          properties:
            versionId:
              type: string
            lastUpdated:
              type: string
            source:
              type: string
        language:
          type: string
        text:
          type: object
          properties:
            status:
              type: string
            div:
              type: string
        status:
          type: string
        type:
          type: object
          properties:
            coding:
              type: object
              properties:
                system:
                  type: string
                code:
                  type: string
                display:
                  type: string
        subject:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        encounter:
          type: object
          properties:
            reference:
              type: string
        date:
          type: string
        author:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        title:
          type: string
        confidentiality:
          type: string
        attester:
          type: object
          properties:
            mode:
              type: string
            time:
              type: string
        custodian:
          type: object
          properties:
            reference:
              type: string
            display:
              type: string
        section:
          type: object
          properties:
            title:
              type: string
            code:
              type: object
              properties:
                coding:
                  type: object
                  properties:
                    system:
                      type: string
                    code:
                      type: string
                    display:
                      type: string
            text:
              type: object
              properties:
                status:
                  type: string
                div:
                  type: string
            entry:
              type: object
              properties:
                reference:
                  type: string
      example:
        resourceType: Composition
        id: '1'
        meta:
          versionId: '1'
          lastUpdated: '2023-03-08T06:42:02.621+00:00'
          source: '#E3Wp8IdPMe08QsvA'
        language: zh-TW
        text:
          status: generated
          div: >-
            <div xmlns="http://www.w3.org/1999/xhtml"><table
            border="1"><caption>出院病摘單</caption><tr><th>身分證字號</th><th>病歷號</th><th>病人姓名</th><th>性別</th><th>出生日期</th><th>文件列印日期</th><th>醫師姓名</th><th>醫師記錄日期時間</th><th>醫院名稱</th><th>住院日期</th><th>出院日期</th><th>轉出醫事機構名稱</th><th>轉入醫事機構名稱</th></tr><tr><td>Z123456789</td><td>123456</td><td>趙錢孫</td><td>男</td><td>1997-01-01</td><td>2010-08-01</td><td>賴一施
            </td><td>2010-07-31</td><td>國立臺灣大學醫學院附設醫院</td><td>2010-07-01</td><td>2010-07-31</td><td>陽明大學附設醫院護理之家</td><td>國立臺灣大學醫學院附設醫院</td></tr></table></div>
        status: preliminary
        type:
          coding:
            - system: http://loinc.org
              code: 18842-5
              display: Discharge Summary
        subject:
          reference: https://fhirtest.uhn.ca/baseR4/Patient/129257
          display: 趙錢孫
        encounter:
          reference: https://fhirtest.uhn.ca/baseR4/Encounter/129801
        date: '2010-08-01T11:34:00'
        author:
          - reference: https://fhirtest.uhn.ca/baseR4/Practitioner/129288
            display: 賴一施
        title: 出院病摘
        confidentiality: 'N'
        attester:
          - mode: professional
            time: '2010-07-31'
        custodian:
          reference: https://fhirtest.uhn.ca/baseR4/Organization/129188
          display: 國立臺灣大學醫學院附設醫院
        section:
          - title: 住院臆斷
            code:
              coding:
                - system: http://loinc.org
                  code: 46241-6
                  display: Hospital admission diagnosis Narrative - Reported
            text:
              status: generated
              div: <div xmlns="http://www.w3.org/1999/xhtml"><br/><table><tr><b>住院臆斷:</b></tr><tr>有軌電車乘客在交通意外事故中與機動車輛碰撞時受傷之初期照護</tr></table></div>
            entry:
              - reference: https://fhirtest.uhn.ca/baseR4/Condition/128907
    Delete_Reaponse_Json:
      type: object
      properties:
        resourceType:
          type: string
        issue:
          type: object
          properties:
            severity:
              type: string
            code:
              type: string
            diagnostics:
              type: string
            details:
              type: object
              properties:
                coding:
                  type: object
                  properties:
                    system:
                      type: string
                    code:
                      type: string
                    display:
                      type: string

      example:
        resourceType: OperationOutcome
        issue:
          - severity: information
            code: informational
            details: 
              coding:
                - system: https://hapifhir.io/fhir/CodeSystem/hapi-fhir-storage-response-code
                  code: SUCCESSFUL_DELETE
                  display: Delete succeeded.
            diagnostics: Successfully deleted 1 resource(s). Took 16ms.
  securitySchemes:
    wiadvance_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://www.wiadvance.com/oauth/authorize
          scopes:
            put: 更新資料
            delete: 刪除資料
      x-tokenInfoFunc: swagger_server.controllers.authorization_controller.check_petstore_auth
      x-scopeValidateFunc: >-
        swagger_server.controllers.authorization_controller.validate_scope_petstore_auth
    api_key:
      type: apiKey
      name: api_key
      in: header
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_api_key